### PR TITLE
Set blank url if range is empty

### PR DESCRIPTION
**Pull request by flexoid**
Move setting url to blank string outside of loop in case if range is empty array. In case when adapt.js is not configured properly yet it helps to avoid requests to .../undefined address, which often lead to application server routing error.

### CODE REVIEW

**Comment by nathansmith** [comment]
Good call. Merged! :)

**Comment by flexoid** [comment]
I forgot to say, but you probably should also update minified version, I just don't know how you do it for your lib. BTW, thanks for the fast merge :)

**Comment by nathansmith** [comment]
I just updated the minified version.

**Comment by flexoid** [comment]
Oh, sorry, didn't notice.

**Comment by nathansmith** [comment]
No problem. Was just letting you know it's updated, that's all. :)

**Pull request merged**
