### PR TITLE
Add Classnames to HTML-Tag for ranges

### PR DESCRIPTION
**Pull request by tobaco**
I needed some classnames for the different ranges to have only one stylesheet and set the styles via this classes.

### CODE REVIEW

**Comment by nathansmith** [comment]
Actually, I was thinking of adding the ability to have a callback function, as that's been requested as a feature.

```
var ADAPT_CONFIG = {
  path: 'assets/css/',
  dynamic: true,
  callback: foobar,
  range: [
    '0px    to 760px  = mobile.css',
    '760px  to 980px  = 720.css',
    '980px  to 1280px = 960.css',
    '1280px to 1600px = 1200.css',
    '1600px to 1920px = 1560.css',
    '1920px           = fluid.css'
  ]
};
```

That way, the callback function would be passed the pixel-width of the browser...

```
if (typeof callback === 'function') {
  callback(width);
}
```

In that callback, the adding of class names, and whatever else, could be handled by the callback. For example...

```
function foobar(width) {
  // Do class replacement/adding here.
}
```

Do you think that would be an acceptable solution? It's not that I don't see the value in adding class names, I do. But if I'm adding a callback, I think that would add a good integration point that could be reusable.

**Comment by tobaco** [comment]
yeah, a callback would be nice, to keep the core lightweight and fast. 
but with only returning the width, the callback-function has to calculate the range again, if someone wants to set the class according to the range. 
how about returning width and the index of the matched element from the range-array

```
if (typeof callback === 'function') {
    callback(width,i);
}
```

**Comment by nathansmith** [comment]
Good point. Maybe the index first then, so the width can be safely ignored?

```
if (typeof callback === 'function') {
  callback(i, width);
}
```

With the function itself...

```
function foobar(i) {
  // Switch-Case, assuming user only cared about index.
}
```

**Comment by valendesigns** [comment]
So would this would work to switch images and keep the page load down for mobile browsers or is the original image going to load then just be switched?

**Comment by nathansmith** [comment]
@valendesigns That'd be up to you to decide. It would work however you wrote the code in your callback function.

**Comment by valendesigns** [comment]
True. I like this implementation, you have my vote.

**Comment by nathansmith** [comment]
If you're looking for something ready-made that handles images, check out this article. These guys are awesome...

http://filamentgroup.com/lab/responsive_images_experimenting_with_context_aware_image_sizing

**Comment by nathansmith** [comment]
Note: Closing this pull request without merging, because the ability to specify a callback has been added...

https://github.com/nathansmith/adapt/blob/master/assets/js/adapt.js

**Pull request closed without merging**
